### PR TITLE
Fix repo `bramus/js-specificity` to `bramus/specificity`

### PR DESCRIPTION
**Pull request by ybiquitous**
I think the repo URL should be <https://github.com/bramus/specificity> now.

If I have misunderstood, feel free to close this PR.

### CODE REVIEW

**Comment by bramus** [comment]
Actions Workflow is failing for an unknown reason though. Think it has to do with me explicitly setting the `ref` on the checkout actions. Will have to take a closer look into it.

**Comment by ybiquitous** [comment]
My fork branch is not `origin/fix-repo`:

https://github.com/bramus/specificity/runs/6423321415?check_suite_focus=true#step:2:3

image

image

I think the `ref` parameter is needless in most cases:

https://github.com/bramus/specificity/blob/97e53aa32f0b5f066b593adc2ee29f2e27f3ca6b/.github/workflows/checks.yml#L18

**Comment by bramus** [comment]
Pushed a fix. Should work now.

**Comment by ybiquitous** [comment]
Thank you. Done.

**Comment by bramus** [comment]
Seems like I fixed only one job, and forgot to fix the others as well. Did an extra push to fix the other jobs as well.

As the one fixed job already verified that it'll work from now on, I'll go ahead and merge this PR. Thanks for testing the updated workflow.

**Comment by ybiquitous** [comment]
Thank you, too. 😄

**Pull request merged**
